### ISSUE TITLE
can't access company email

### ISSUE THREAD

**Issue by jic007** [allanvc/mRpostman#16]
I tried to use the package on my company outlook email; office365 but not sure it fails as access is denied

normally if I login through browsers, it sends OTP code ; 2 way authentication. 

Thus, is the package capable of handling this? if so how? 

I couldn't find something related in the documentation

appreciate your help

**Comment by tommandru** [comment]
Hello @jic007 ,  I have the same issue. I thought it was because IMAP wasn't enabled for my account. Despite getting it enabled , I am still getting the same error.

**Comment by allanvc** [comment]
Hi,
Thank you for your message!
Did you mean an OAuth2 connection?
I would love to help but this is hard to solve on my end. Theoretically speaking, mRpostman can handle this type of connection because cURL can handle it. Therefore, it will be just a matter of correctly generating a bearer token for example, and passing it through `configure_imap()`. Maybe the vignette on OAuth2 via Gmail would be a good start. Even so, you would still (likely) need some help from your company's IT department to correctly do all the procedures or even ask for some security modifications on the server side. Please provide me with more details on the type of connection you are trying to establish, etc, so that I can be of more help.
