### ISSUE TITLE
Getting strange html artifacts with fetch_text

### ISSUE THREAD

**Issue by StevenLarsen89** [allanvc/mRpostman#4]
Hi,

I want to use fetch_text to extract links from daily e-mails. However, when I use it I get some weird html artifacts: "\r\n" and "3D" scattered throughout the extracted text.

`out <- con$search_on(date_char = "15-Nov-2020") %>% 
  con$fetch_text(write_to_disk = FALSE, 
                 keep_in_mem = TRUE)`

This results in the following html: 

`<html>\r\n<head>\r\n<meta http-equiv=3D\"Content-Type\" content=3D\"text/html; charset=3Dus-ascii\"=\r\n></head>\r\n<header><style>body, p {font-family:arial, helvetica, sans-serif; font-size=\r\n: 13px;} td, th { font-size: 11px;  padding: 5px; } th { background-color: =\r\n#8DBF57; color: white; } table { border: solid 1px; border-color: #B8B7B7; =\r\nwidth: 100%; } a { color: #3D7EA9; text-decoration: none; } ....`

The artifacts also appear inside the links. Is there a way to extract the mail text in plaintext? Or some setting that I have not used correctly?

Regards,
Steven

**Comment by allanvc** [comment]
Hi Steven, sorry for the delay in responding to you.
The artifacts you see are due to the fact that the message you are fetching has HTML content. `fetch_text()` does not excute any cleaning task. It extracts the text part "as is".
I am currently working on a solution to help users to visualize a cleaner content, also decoding quoted printable characters and some HTML tags.
Please, install the dev version of the package (`devtools::instal_github("allanvc/mRpostman"`) and try to use the `clean_msg_text()` function. In your case, it would be `clean_out <- clean_msg_text(out)`. It might be necessary to do more cleaning steps, which can be easily achieved with some regex/gsub combo. Also, if you just want to visualize a prettier version of the text without having to apply some regex, I suggest using `writeLines(clean_out[[i]])`, where `i` can be any index of your output list after the cleaning step with `clean_msg_text()`.

**Comment by allanvc** [comment]
One last remark...

If your fetched messages have attachments, the recommended way of extracting the text is using `fetch_body(..., mime_level = 1L)` instead of `fetch_text()`. After, you can use the `clean_msg_text()` on the fetched output. The `mime_level` argument is only available in the development version, but will be incorporated in the next CRAN version.
